#!/bin/bash

echo "🚀 ML Pipeline Manual Triggers"
echo "=============================="
echo ""
echo "Trigger pipelines individually:"
echo ""
echo "1️⃣  Data Generation (runs daily):"
echo "   astro dev run dags trigger 01_data_generation_pipeline"
echo ""
echo "2️⃣  Data Preparation (waits for generation):"
echo "   astro dev run dags trigger 02_data_preparation_pipeline"  
echo ""
echo "3️⃣  Model Training (manual trigger won't skip):"
echo "   astro dev run dags trigger 03_model_training_pipeline"
echo ""
echo "📊 Batch Predictions (weekly):"
echo "   astro dev run dags trigger batch_prediction_pipeline"
echo ""
echo "🔄 Or run all three in sequence:"
echo "   ./scripts/trigger_all_pipelines.sh"
echo "" 